FIREBASE_ML_KEY = "FIREBASE_ML"

FIREBASE_ML_MODEL_NAME_KEY = "FIREBASE_ML_MODEL_NAME"
FIREBASE_ML_MODEL_TAGS_KEY = "FIREBASE_ML_MODEL_TAGS"

FIREBASE_SERVICE_ACCOUNT_KEY = "FIREBASE_SERVICE_ACCOUNT"
FIREBASE_GCS_BUCKET_KEY = "FIREBASE_GCS_BUCKET"

OPTIONS_KEY = "OPTIONS"
