steps:
# Clone the repository.
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--single-branch', '--branch',
         '$_BRANCH', '$_BASE_URL/$_REPO_NAME',
         '--depth', '1',
         '--verbose']
  id: 'Clone Repository'

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'models/model.py models/preprocessing.py', 'gs://$_PROJECT-kubeflowpipelines-default/modules']
  dir: '$_REPO_NAME/$_PIPELINE_PATH'
  id: 'Copy Modules'
  waitFor: ['Clone Repository']

- name: 'tensorflow/tfx:latest'
  entrypoint: 'tfx'
  args: ['pipeline', 'create',
          '--pipeline-path', 'kubeflow_runner.py',
          '--engine', 'vertex',
        ]
  dir: '$_REPO_NAME/$_PIPELINE_PATH'
  id: 'Create Pipeline'
  waitFor: ['Copy Modules']

# --project=gcp-ml-172005 --region=us-central1
- name: 'tensorflow/tfx:latest'
  entrypoint: 'tfx'
  args: ['run', 'create',
          '--engine', 'vertex',
          '--pipeline-name', '$_PIPELINE_NAME',
          '--project', '$_PROJECT',
          '--region', '$_REGION'
        ]
  dir: '$_REPO_NAME/$_PIPELINE_PATH'
  id: 'Create Pipeline Run'
  waitFor: ['Create Pipeline']