name: Trigger Cloud Build

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository for the pipeline'
        required: true
        default: 'https://github.com/deep-diver/complete-mlops-system-workflow.git'
      branch:
        description: 'Repository for the pipeline'
        required: true
        default: 'main'
      gcpRegion:
        description: 'GCP Region for Vertex AI Pipeline'
        required: true
        default: 'us-central1'
      pipelineName:
        description: 'TFX Pipeline Name to Trigger'
        required: true
        default: 'img-classification'
      spanPattern:
        description: 'Span Numbers (regex)'
        required: true
        default: '[12]'    
    
jobs:
  build:
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v2.4.2
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
                
    - name: 'Trigger Cloud Build'
      run: |
        gcloud builds submit --no-source \
          --quiet \
          --timeout=60m \
          --config=build/trigger-pipeline-deployment.yaml \
          --substitutions=_REPO="${{ github.event.inputs.repository }}",\
                          _BRANCH=${{ github.event.inputs.branch }},\
                          _REGION=${{ github.event.inputs.gcpRegion }},\
                          _PIPELINE_NAME=${{ github.event.inputs.pipelineName }},\
                          _SPAN=${{ github.event.inputs.spanPattern }}
