name: Trigger Cloud Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  SUBSTITUTIONS: | 
    _PROJECT=gcp-ml-172005,
    _REGION=us-central1,
    _REPO_URL=https://github.com/deep-diver/complete-mlops-system-workflow,
    _BRANCH=main,
    _PIPELINE_NAME=tfx-pipeline
        
jobs:
  build:
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      
    - name: 'Print Substiution'
      run: |
        echo $SUBSTITUTIONS

#     - name: 'Check Changes in the Training Pipeline'
#       uses: dorny/paths-filter@v2
#       id: training_pipeline_change
#       with:
#           filters: |
#               src:
#                 - 'training_pipeline/**'
                
    - name: 'Trigger Cloud Build'
#       if: steps.training_pipeline_change.outputs.src == 'true'
      run: |+
        gcloud builds submit 
        --no-source 
        --timeout=60m 
        --config build/pipeline-deployment.yaml 
        --substitutions $SUBSTITUTIONS 
        --machine-type=n1-highcpu-8
